# Generated by Django 2.2.17 on 2022-08-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
