# Generated by Django 2.2.17 on 2022-08-24 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220823_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alts',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
